# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "well_formed", path: "../../"

gem "rake", "~> 13.0"
gem "rspec", "~> 3.0"
gem "activerecord", require: false
gem "sqlite3"
gem "standard", "~> 1.3"
gem "rubocop-rails", require: false
